### PR TITLE
Make pacakge optional when using -r/--requirements

### PR DESCRIPTION
**Pull request by prologic**
Just noted that it's useful to make `package` optional in this case.

### CODE REVIEW

**Comment by benesch** [comment]
Hmm—doesn't `*` imply that already? (Zero or more.)

https://docs.python.org/3/library/argparse.html#nargs

**Comment by prologic** [comment]
Unfortunately not (_at least in testing_).

**Comment by prologic** [comment]
The [argparse documetnation](https://docs.python.org/2/library/argparse.html#nargs) seems to back this up too. I don't think `*` actually means _zero or more_ :/

**Comment by prologic** [comment]
The lack of `*` meaning _zero or more_ could also be a bug in Python 2.6.x which we are still on largely here at APN

**Comment by prologic** [comment]
Actually let me test this again on Python 2.6 :) Just to be sure!

**Comment by prologic** [comment]
I think I jumped the gun with this one haha :) Sorry! Must have got confused by something else that was going on!

**Pull request closed without merging**
